# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lycee2.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 641, 381))
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.comboBox_5 = QtWidgets.QComboBox(self.tab_5)
        self.comboBox_5.setGeometry(QtCore.QRect(20, 30, 101, 23))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_6 = QtWidgets.QComboBox(self.tab_5)
        self.comboBox_6.setGeometry(QtCore.QRect(140, 30, 151, 23))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_7 = QtWidgets.QComboBox(self.tab_5)
        self.comboBox_7.setGeometry(QtCore.QRect(300, 30, 151, 23))
        self.comboBox_7.setObjectName("comboBox_7")
        self.label_16 = QtWidgets.QLabel(self.tab_5)
        self.label_16.setGeometry(QtCore.QRect(20, 10, 59, 15))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.tab_5)
        self.label_17.setGeometry(QtCore.QRect(140, 10, 59, 15))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.tab_5)
        self.label_18.setGeometry(QtCore.QRect(300, 10, 71, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.tab_5)
        self.label_19.setGeometry(QtCore.QRect(470, 10, 59, 15))
        self.label_19.setObjectName("label_19")
        self.comboBox_8 = QtWidgets.QComboBox(self.tab_5)
        self.comboBox_8.setGeometry(QtCore.QRect(470, 30, 151, 23))
        self.comboBox_8.setObjectName("comboBox_8")
        self.label_20 = QtWidgets.QLabel(self.tab_5)
        self.label_20.setGeometry(QtCore.QRect(20, 70, 41, 16))
        self.label_20.setObjectName("label_20")
        self.dateEdit = QtWidgets.QDateEdit(self.tab_5)
        self.dateEdit.setGeometry(QtCore.QRect(210, 130, 110, 24))
        self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2019, 11, 17), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_9.setGeometry(QtCore.QRect(360, 130, 80, 23))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_10.setGeometry(QtCore.QRect(300, 70, 80, 23))
        self.pushButton_10.setObjectName("pushButton_10")
        self.comboBox_14 = QtWidgets.QComboBox(self.tab_5)
        self.comboBox_14.setGeometry(QtCore.QRect(90, 70, 161, 23))
        self.comboBox_14.setObjectName("comboBox_14")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_3.setGeometry(QtCore.QRect(100, 130, 61, 23))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_6 = QtWidgets.QLabel(self.tab_5)
        self.label_6.setGeometry(QtCore.QRect(20, 130, 59, 15))
        self.label_6.setObjectName("label_6")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(40, 30, 59, 15))
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(30, 60, 111, 23))
        self.comboBox.setObjectName("comboBox")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(250, 60, 121, 23))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(420, 60, 80, 23))
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(40, 110, 59, 15))
        self.label_3.setObjectName("label_3")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab)
        self.comboBox_2.setGeometry(QtCore.QRect(30, 140, 141, 23))
        self.comboBox_2.setObjectName("comboBox_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_2.setGeometry(QtCore.QRect(200, 140, 91, 23))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_5.setGeometry(QtCore.QRect(312, 140, 91, 23))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_3.setGeometry(QtCore.QRect(420, 140, 80, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab)
        self.pushButton_4.setGeometry(QtCore.QRect(520, 140, 80, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(40, 190, 81, 16))
        self.label_4.setObjectName("label_4")
        self.comboBox_3 = QtWidgets.QComboBox(self.tab)
        self.comboBox_3.setGeometry(QtCore.QRect(30, 220, 141, 23))
        self.comboBox_3.setObjectName("comboBox_3")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_6.setGeometry(QtCore.QRect(200, 220, 113, 23))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_7.setGeometry(QtCore.QRect(320, 220, 113, 23))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab)
        self.pushButton_5.setGeometry(QtCore.QRect(450, 220, 80, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab)
        self.pushButton_6.setGeometry(QtCore.QRect(550, 220, 80, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(40, 270, 71, 16))
        self.label_5.setObjectName("label_5")
        self.comboBox_4 = QtWidgets.QComboBox(self.tab)
        self.comboBox_4.setGeometry(QtCore.QRect(40, 300, 131, 23))
        self.comboBox_4.setObjectName("comboBox_4")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_8.setGeometry(QtCore.QRect(200, 300, 113, 23))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab)
        self.pushButton_7.setGeometry(QtCore.QRect(350, 300, 80, 23))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab)
        self.pushButton_8.setGeometry(QtCore.QRect(460, 300, 80, 23))
        self.pushButton_8.setObjectName("pushButton_8")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(20, 30, 59, 15))
        self.label_7.setObjectName("label_7")
        self.comboBox_10 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_10.setGeometry(QtCore.QRect(90, 30, 141, 23))
        self.comboBox_10.setObjectName("comboBox_10")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(300, 30, 59, 15))
        self.label_8.setObjectName("label_8")
        self.comboBox_11 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_11.setGeometry(QtCore.QRect(390, 30, 161, 23))
        self.comboBox_11.setObjectName("comboBox_11")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(20, 90, 59, 15))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(300, 90, 71, 16))
        self.label_10.setObjectName("label_10")
        self.comboBox_12 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_12.setGeometry(QtCore.QRect(90, 90, 141, 23))
        self.comboBox_12.setObjectName("comboBox_12")
        self.comboBox_13 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_13.setGeometry(QtCore.QRect(390, 90, 161, 23))
        self.comboBox_13.setObjectName("comboBox_13")
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(40, 150, 59, 15))
        self.label_11.setObjectName("label_11")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(110, 150, 113, 23))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.comboBox_5.currentTextChanged['QString'].connect(MainWindow.fill_combobox_6)
        self.comboBox_8.currentTextChanged['QString'].connect(MainWindow.update_note)
        self.comboBox_7.currentTextChanged['QString'].connect(MainWindow.update_note)
        self.comboBox_6.currentTextChanged['QString'].connect(MainWindow.update_note)
        self.comboBox.currentTextChanged['QString'].connect(MainWindow.fill_combobox_2)
        self.pushButton_3.clicked.connect(MainWindow.ajoute_eleve)
        self.pushButton_4.clicked.connect(MainWindow.supprime_eleve)
        self.pushButton_5.clicked.connect(MainWindow.ajoute_professeur)
        self.pushButton_7.clicked.connect(MainWindow.ajoute_discipline)
        self.pushButton_9.clicked.connect(MainWindow.ajoute_note)
        self.pushButton_10.clicked.connect(MainWindow.supprime_note)
        self.comboBox_10.currentTextChanged['QString'].connect(MainWindow.update_eleves)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Lycée"))
        self.label_16.setText(_translate("MainWindow", "Classe"))
        self.label_17.setText(_translate("MainWindow", "Elève"))
        self.label_18.setText(_translate("MainWindow", "Professeur"))
        self.label_19.setText(_translate("MainWindow", "Discipline"))
        self.label_20.setText(_translate("MainWindow", "Note"))
        self.pushButton_9.setText(_translate("MainWindow", "Ajouter"))
        self.pushButton_10.setText(_translate("MainWindow", "Supprimer"))
        self.label_6.setText(_translate("MainWindow", "Nouvelle"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "notes"))
        self.label_2.setText(_translate("MainWindow", "Classes"))
        self.lineEdit.setText(_translate("MainWindow", "Nom de la classe ?"))
        self.pushButton.setText(_translate("MainWindow", "Ajouter"))
        self.label_3.setText(_translate("MainWindow", "Eleves"))
        self.lineEdit_2.setText(_translate("MainWindow", "Nom"))
        self.lineEdit_5.setText(_translate("MainWindow", "Prenom"))
        self.pushButton_3.setText(_translate("MainWindow", "Ajouter"))
        self.pushButton_4.setText(_translate("MainWindow", "Supprimer"))
        self.label_4.setText(_translate("MainWindow", "Professeurs"))
        self.lineEdit_6.setText(_translate("MainWindow", "Nom"))
        self.lineEdit_7.setText(_translate("MainWindow", "Prenom"))
        self.pushButton_5.setText(_translate("MainWindow", "Ajouter"))
        self.pushButton_6.setText(_translate("MainWindow", "Supprimer"))
        self.label_5.setText(_translate("MainWindow", "Disciplines"))
        self.lineEdit_8.setText(_translate("MainWindow", "Nom"))
        self.pushButton_7.setText(_translate("MainWindow", "Ajouter"))
        self.pushButton_8.setText(_translate("MainWindow", "Supprimer"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Admin"))
        self.label_7.setText(_translate("MainWindow", "Classe"))
        self.label_8.setText(_translate("MainWindow", "Eleve"))
        self.label_9.setText(_translate("MainWindow", "Discipline"))
        self.label_10.setText(_translate("MainWindow", "Professeur"))
        self.label_11.setText(_translate("MainWindow", "Moyenne"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Moyennes"))
